<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Cloud.PubSub.V1" />
    <PackageReference Include="HdrHistogram" />
    <PackageReference Include="DogStatsD-CSharp-Client" />
  </ItemGroup>
</Project>
